### PR TITLE
Indicate that wallet mode is needed before exiting

### PR DESCRIPTION
**Pull request by verretor**
The error message didn't give much indications as to what was wrong and how to fix it.

### CODE REVIEW

**Comment by verretor** [comment]
Sorry about that merge. At least, now you know there are no conflicts.

**Comment by verretor** [comment]
Rebased.

**Comment by verretor** [comment]
Yes I know this would be ideal but it doesn't crash at that point though.

It happens at that line:
unspentAddresses <- bitcoinClient.listUnspentAddresses

But I didn't find a way to verify if wallet mode was enabled without getting "Method not found" first. Is there an easy way to do that?

**Comment by verretor** [comment]
A way this could have been done before is with "getinfo" and look for "walletversion". "getinfo" is deprecated and will be fully removed in 0.16. I tried "getwalletinfo". It returns "Method not found" if you don't have wallet enabled.

So, I'm not sure there's a way to verify if the wallet is enabled without getting the error first.

**Comment by pm47** [comment]
> I'm not sure there's a way to verify if the wallet is enabled without getting the error first.

Getting an error is ok, eg something like this should work:

```
diff --git a/eclair-core/src/main/scala/fr/acinq/eclair/Setup.scala b/eclair-core/src/main/scala/fr/acinq/eclair/Setup.scala
index badf942..cba632d 100644
--- a/eclair-core/src/main/scala/fr/acinq/eclair/Setup.scala
+++ b/eclair-core/src/main/scala/fr/acinq/eclair/Setup.scala
@@ -67,6 +67,7 @@ class Setup(datadir: File, overrideDefaults: Config = ConfigFactory.empty(), act
         port = config.getInt("bitcoind.rpcport")))
       val future = for {
         json <- bitcoinClient.rpcClient.invoke("getblockchaininfo").recover { case _ => throw BitcoinRPCConnectionException }
+        _ <- bitcoinClient.rpcClient.invoke("getbalance").recover { case _ => throw BitcoinWalletDisabledException }
         progress = (json \ "verificationprogress").extract[Double]
         chainHash <- bitcoinClient.rpcClient.invoke("getblockhash", 0).map(_.extract[String]).map(BinaryData(_)).map(x => BinaryData(x.reverse))
         bitcoinVersion <- bitcoinClient.rpcClient.invoke("getnetworkinfo").map(json => (json \ "version")).map(_.extract[String])
@@ -232,4 +233,6 @@ case object BitcoinZMQConnectionTimeoutException extends RuntimeException("could

 case object BitcoinRPCConnectionException extends RuntimeException("could not connect to bitcoind using json-rpc")

+case object BitcoinWalletDisabledException extends RuntimeException("bitcoind must have wallet support enabled")
+
 case object EmptyAPIPasswordException extends RuntimeException("must set a user/password for the json-rpc api")
```

**Comment by verretor** [comment]
Seems to me it will be pretty much a copy/paste of your code lol.

**Comment by verretor** [comment]
I reverted the original commit. I know you squash commits and I just wanted to keep the history of this pull request. Your version of the code is much more concise than mine. I like it.

I tested it with bitcoind with and without wallet support and can confirm it works as expected.

**Comment by pm47** [comment]
Thanks!

**Pull request merged**
