### PR TITLE
Fix JSON Postgres index on channel's `remote_node_id`

### PR DESCRIPTION
**Pull request by t-bast**
We're creating an index on the `remote_node_id` based on the channel's JSON serialization, which isn't very robust. The data model changes for splicing have changed the JSON format and thus broken that index.

I'm not sure how to test this and prevent future regressions...it would probably be best to add a dedicated `remote_node_id` column if we want to preserve that index instead of relying on JSON.

Thanks @rorp for reporting this bug.

### CODE REVIEW

**Comment by pm47** [comment]
This looks correct, but wouldn't affect existing databases. I believe we should add the following to the release note:

## Major changes

### Data model

The database model has been completely reworked to handle splices. Mainly, a channel can have several commitments in parallel.

For operators that use Postgres as database backend:
1. Set `eclair.db.postgres.reset-json-columns = true` and restart eclair
2. Set `eclair.db.postgres.reset-json-columns = false` (no need to restart)
3. Run the following database command:
```sql
DROP INDEX local.local_channels_remote_node_id_idx;
CREATE INDEX local_channels_remote_node_id_idx ON local.channels ((json->'commitments'->'params'->'remoteParams'->>'nodeId'));
```

**Comment by rorp** [comment]
That can be done automatically in a migration.

The migration can use `Connection. getMetaData().getIndexInfo()` to check if the correct index exists.
If not the migration would drop the old index (if it exists at all) and create the correct one.

**Comment by rorp** [comment]
Such a migration can be reused next time the JSON structure changes.

**Review by pm47 — COMMENTED** [review]
> I added an explicit column for remote_node_id in https://github.com/ACINQ/eclair/commit/2dc9280e5ad38be734d8a3b983f5d3144e9e71be, it is cleaner than relying on JSON fields.

👍 

> I don't know if we should still add details in the release notes about resetting the JSON column, it will be done automatically on a per-channel basis as channels are updated, so it's not necessary for the node to correctly operate, but can be nice for users that rely on direct SQL queries for auditing. What do you think?

I think a mention is still nice, maybe as a simple recommendation.

**Pull request merged**
