### PR TITLE
Monitoring of Eventbus and Gauges on Channels/Nodes

### PR DESCRIPTION
**Pull request by n1bor**

### CODE REVIEW

**Comment by n1bor** [comment]
@pm47  Been running this for 10 hrs on 280 channels:
https://pastebin.com/raw/vhvvJj3F

Seems to average almost 80 channel updates a second - which seems totally unnecessary.

Wondering why we need updates from all the peers? Surely if we just request updates from 8 that would be enough?

**Comment by n1bor** [comment]
This is a perfect one to add as a plugin...

**Comment by n1bor** [comment]
Add grafana stats from API if anyone interested:
https://lightningconductor.net/grafana/

**Comment by t-bast** [comment]
This PR is superceded by https://github.com/ACINQ/eclair/pull/1126.
We will gradually add more metrics / spans as we test them under load.

**Pull request closed without merging**
