### PR TITLE
Explicitely ack all relayed messages

### LINKED ISSUE #378: Expired payment don't get failed if sender is offline at expiration time
Setup is as follows: `A (sender)` -> `B` -> `C (malicious receiver)`

Scenario 1:
1. `A` sends an HTLC of `1,000,000 SAT` to `C`
2. `C` accepts an HTLC and does nothing
3. `A` stays online
4. 9 blocks pass, `B` breaks `B -> C` channel and fails `A`'s HTLC

Scenario 2:
1. `A` sends an HTLC of `1,000,000 SAT` to `C`
2. `C` accepts an HTLC and does nothing
3. `A` goes offline
4. 9 blocks pass, `B` breaks `B -> C` channel
5. `A` becomes online but `B` does not fail `A`'s HTLC
6. 144 more blocks pass and `A` initiates an uncooperative closing because of expired HTLC

### PR DESCRIPTION
**Pull request by pm47**
In order to gracefully handle cases when the counterparty goes online while we are in
the middle of processing payments, we need to explicitely ack all
`fulfill`/`fail`/`fail_malformed` messages.

We previously only acked `fulfill` messages.

This fixes #378.

### CODE REVIEW

**Comment by pm47** [comment]
@btcontract can you check if that solves the scenario you describe in #378? Thanks!

**Comment by btcontract** [comment]
It works but not always, here are the details:

Scenario 1:
1. `A` sends apayment to `C`, `C` does nothing, `A` goes offline
2. 9 blocks are generated, `B -> C` channel is broken, no more blocks generated
3. `A` becomes online but it's payment stays in-flight after channel reestablishment
4. one more block is generated, `A`'s payment is failed.

Scenario 2:
1. `A` sends apayment to `C`, `C` does nothing, `A` goes offline
2. 9 blocks are generated, `B -> C` channel is broken, more blocks generated, say 10 but it does not matter
3. `A` becomes online but it's payment stays in-flight after channel reestablishment and does not get failed on new generated blocks up until `A` initiates an uncooperative closing.

**Comment by pm47** [comment]
I see the issue now. Making a second pass...

**Comment by pm47** [comment]
@btcontract how about now?

**Comment by btcontract** [comment]
Now it works fine in both scenarios described above: payment is being failed on reestablishment. But once again that's only true for large enough payments, small ones are never getting failed, even if the sender is online all the time.

**Comment by pm47** [comment]
def602c fixes #377 (small htlcs not being failed), but I'm not sure that's the best way to handle that, I need to think a bit more about it

8e54971 fixes #376

**Pull request merged**
