### PR TITLE
Fix test when run in Intellij (#2288)

### PR DESCRIPTION
**Pull request by barrybecker4**
The path needed to be adjusted from "target" to "eclair-core/target".
Also fixed a typo in a comment.

### CODE REVIEW

**Review by t-bast — COMMENTED** [review]
Thanks! Works on my machine, @pm47 can you test on yours since you have a different setup?

**Review by pm47 — APPROVED** [review]
LGTM. Welcome to the project @barrybecker4!

IIRC Intellij used to pick the current dir based on how you executed the test, usually I edited the `Working Directory` in the test configuration to make it work. I am guessing they did something recently because now it points to `$PROJECT_DIR$`.

**Comment by pm47** [comment]
@barrybecker4 I'm wondering, are you able to merge the PR after I acked?

**Comment by barrybecker4** [comment]
@pm47  No. I do not seem to have permission.

**Pull request merged**
