### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by verretor**
Specify that the Bitcoin Core node must have wallet enabled.

### CODE REVIEW

**Comment by verretor** [comment]
I think it is important to specify. I had compiled Bitcoin with --disable-wallet and when running Eclair, I got: "Method not found (code: -32601)". Might be good to also tell the user to compile Bitcoin with wallet support when that error happens.

**Comment by pm47** [comment]
agreed

nitpick: can you put it in italic for consistency with the rest? thanks

**Comment by verretor** [comment]
Oh yes. I didn't realize it was in Italic because of Vim lol.

**Comment by verretor** [comment]
Looks good now.

**Comment by pm47** [comment]
Thanks!

**Pull request merged**
