### PR TITLE
Add `listreceivedpayments` RPC call

### PR DESCRIPTION
**Pull request by rorp**

### CODE REVIEW

**Comment by t-bast** [comment]
Thanks, I think this is useful! A couple high-level comments:

- I don't think exposing `listexpiredinvoices` to the API is useful (especially since those invoices get automatically deleted from the DB at regular intervals), why did you add it?
- I think `listpaidinvoices` would make more sense if it were called `listreceivedpayments` and if it returned a `Seq[IncomingPayment]` instead of just the `Invoice`, that seems to be the desired feature, isn't it?

**Comment by rorp** [comment]
> * I don't think exposing `listexpiredinvoices` to the API is useful (especially since those invoices get automatically deleted from the DB at regular intervals), why did you add it?

It can be useful for accounting. Also, automatic purges can be disabled, and when enabled they happen in specific intervals (24h by default).

> * I think `listpaidinvoices` would make more sense if it were called `listreceivedpayments` and if it returned a `Seq[IncomingPayment]` instead of just the `Invoice`, that seems to be the desired feature, isn't it?

Good idea!

**Review by t-bast — DISMISSED** [review]
LGTM, thanks!

**Comment by t-bast** [comment]
Damn, there is a (trivial) conflict in the payment tests, can you rebase on master?

**Review by t-bast — APPROVED** [review]
LGTM, thanks!

**Pull request merged**
