### PR TITLE
Add support for the `signet` test network

### PR DESCRIPTION
**Pull request by remyers**
Requires 0.24 version of bitcoin-lib ([#70](https://github.com/ACINQ/bitcoin-lib/pull/70)) which exposes hash of signet genesis block.

### CODE REVIEW

**Review by t-bast — COMMENTED** [review]
There are a few more things you need to modify:

- in `reference.conf` you should update the documentation for the `chain` parameter to mention signet support
- in `NodeParams` you should update the `chain2Hash` map to include the signet case
- you should update the release doc to mention signet support in the `Miscellaneous improvements and bug fixes` section

Otherwise LGTM :+1:

**Comment by remyers** [comment]
Tested (by-hand) signet channel open/sendtoroute/close using config files and script commands from [lightning-cfg](https://github.com/remyers/lightning-cfg/tree/signet) after [updating for signet](https://github.com/remyers/lightning-cfg/commit/637d891b44c7c5630aecfa0c50528740a383afe6).

final tx: https://mempool.space/signet/tx/950936af3ad8aa1fd916c4d9b9cc43cfec50806c0a0147c3339420952c17acf9

**Comment by remyers** [comment]
> * you should update the release doc to mention signet support in the `Miscellaneous improvements and bug fixes` section

fixed in [75c40c1](https://github.com/ACINQ/eclair/pull/2387/commits/75c40c1f999b1186c7fe45b66c62eacc5cab249d)

**Comment by remyers** [comment]
@t-bast 
> * in `reference.conf` you should update the documentation for the `chain` parameter to mention signet support
> 
> * in `NodeParams` you should update the `chain2Hash` map to include the signet case

Hmm, these should be changed in the origin commit [5aa0819](https://github.com/ACINQ/eclair/pull/2387/commits/5aa0819b44bc66ca454cc417384fbf73d7bc4e19).

**Comment by remyers** [comment]
MempoolTxMonitor successfully detected the channel close on Signet:
image

**Review by t-bast — DISMISSED** [review]
> Hmm, these should be changed in the original commit [5aa0819](https://github.com/ACINQ/eclair/pull/2387/commits/5aa0819b44bc66ca454cc417384fbf73d7bc4e19).

Right, my bad, github had a filter on only the last commits!
I just reviewed the whole PR, LGTM, this is thorough and well done :+1:

**Review by t-bast — APPROVED** [review]

**Pull request merged**
