### PR TITLE
[WIP] Rework fulfill/fail commands acknowledgements

### PR DESCRIPTION
**Pull request by pm47**
When we receive an `UpdateFulfillHtlc` from a downstream channel, it is critical that we don't lose it because it allows us to pull funds from some upstream channel. But this upstream channel may very well be currently `OFFLINE` and unable to update the commitment right away, so we need to remember it for later. Same applies to an `UpdateFailHtlc` (even if it is less critical), because we don't want the upstream htlc to timeout and cause a channel to get closed.

We were previously relying on a `CommandBuffer` actor, which made the flow a little cumbersome and not easy to understand. 

Instead, when a channel is in `OFFLINE` state and can't process a `CMD_FULFILL_HTLC`/`CMD_FAIL_HTLC`/`CMD_FAIL_MALFORMED_HTLC`, the channel itself is responsible for storing the command, and will reprocess it when it goes online again or gets closed.

### CODE REVIEW

**Comment by pm47** [comment]
NB: with this PR, fulfill/fails won't be persisted if the channel is very busy (mailbox full).

**Comment by btcontract** [comment]
@pm47 I'm trying to understand this: according to docs akka uses an unbounded mailbox by default, so it can only fail if we run out of physical memory. Is that correct or are there other factors at play?

**Comment by pm47** [comment]
@btcontract The problem is that messages aren't persisted.

**Comment by btcontract** [comment]
@pm47 ah, I think I underatand now: it's about `fail/fulfill` messages sitting in a mailbox for a long time? (could be seconds yet Eclair can still be shut down during that time).

FWIW when reading about mailboxes I've noticed this one: https://doc.akka.io/japi/akka/current/akka/dispatch/UnboundedControlAwareMailbox.html (also `UnboundedPriorityMailbox`, `UnboundedStablePriorityMailbox`), haven't tested how they work but parhaps it's the right tool if I get a problem right.

**Comment by pm47** [comment]
> ah, I think I underatand now: it's about fail/fulfill messages sitting in a mailbox for a long time? (could be seconds yet Eclair can still be shut down during that time).

Exactly. That's a tricky problem and this PR failed to address it.

**Comment by pm47** [comment]
Superseded by #1476.

**Pull request closed without merging**
