### PR TITLE
Add an option to avoid bitcoin sig checking for ChannelAnnouncement

### PR DESCRIPTION
**Pull request by btcontract**
This change will make it easier to check public hosted channels' announcements which don't have a chain funding part.

### CODE REVIEW

**Comment by pm47** [comment]
This is starting to feel very hackish...

**Comment by btcontract** [comment]
I guess this post can explain best what I'm up to: https://www.rene-pickhardt.de/index.html%3Fp=2131.html

tl/dr it's not as bad as it may seem if used right.

**Comment by btcontract** [comment]
Another point is this is needed for a plugin only, won't be used in core anywhere. I could just copy related code without bitcoin sig part but doing it this way seems nicer.

**Comment by t-bast** [comment]
I don't like this change either, and I really want to avoid adding this footgun in eclair-core.
It's very easy to avoid needing it: hosted channels can simply use the same public key in `nodeId` and `bitcoinKey`, and provide a valid signature of the message.

**Comment by btcontract** [comment]
Thanks for the suggestion, my initial plan was that one of distinguishing parts of PHC announcements is some predetermined static bitcoin key values and zeroed out bitcoin signatures, but bitcoin keys equal to node keys seem an equally good idea, I'll go with it.

**Pull request closed without merging**
