### PR TITLE
Add `ChannelAborted` event

### PR DESCRIPTION
**Pull request by t-bast**
That additional event lets subcribers know when a channel was closed without ever being used.

The possible flows for a channel lifecycle are now:

- ChannelCreated -> ChannelOpened -> ChannelAborted (when we don't have funds in the channel)
- ChannelCreated -> ChannelOpened -> ChannelClosed (when we have funds in the channel)
- ChannelCreated -> ChannelAborted (when we don't have funds in the channel)
- ChannelCreated -> ChannelClosed (when we have funds in the channel)
- ChannelAborted (when we don't have funds in the channel)
- ChannelAborted -> ChannelClosed (when we have funds in the channel)

### CODE REVIEW

**Comment by remyers** [comment]
I can see how this will greatly simplify PR #2552! In that context, are these changes meant to ensure that we can rely on the fact that any time a channel actor is spawned, it will end up emitting either `ChannelOpened`, `ChannelClosed` or `ChannelAborted` at some point? 

For example, I can see that in the case of a channel receiving `BITCOIN_FUNDING_PUBLISH_FAILED` then the `ChannelErrorOccurred` event will be emitted but not `ChannelClosed` or `ChannelAborted`. So perhaps these changes only ensure `ChannelOpened`, `ChannelClosed` or `ChannelAborted` for a channel where we are not the initiator. What is the set of `ChannelEvents` we can expect before a channel actor is finally finished? is that set different if we initiate the channel open? 

I want to make sure I understand how the changes to the Channel FSM work. My understanding is that the new `ChannelAborted` event adds three new lifecycle sequences to the two that already produced `ChannelClosed` :

 1) when a peer closes without our node having any value at stake in the channel (`nothingAtStake(...)` is true):
- ChannelCreated -> ChannelOpened -> ChannelAborted
 2) the FSM is transitioning to the `CLOSED` state and is in a transient state prior to `ChannelCreated` being emitted:
- ChannelAborted
 3) the FSM transitioning to the `CLOSED` state and is in a state waiting for the funding tx to confirm:
- ChannelCreated -> ChannelAborted

**Comment by t-bast** [comment]
> are these changes meant to ensure that we can rely on the fact that any time a channel actor is spawned, it will end up emitting either ChannelOpened, ChannelClosed or ChannelAborted at some point?

Yes exactly!

> For example, I can see that in the case of a channel receiving BITCOIN_FUNDING_PUBLISH_FAILED then the ChannelErrorOccurred event will be emitted but not ChannelClosed or ChannelAborted. 

In that case, the `ChannelAborted` event should be emitted in the `onTransition` block. If that's not the case, that is a bug! Can you point me to a specific line of code where this may happen?

> I want to make sure I understand how the changes to the Channel FSM work. My understanding is that the new ChannelAborted event adds three new lifecycle sequences to the two that already produced ChannelClosed

That looks correct!

**Comment by t-bast** [comment]
I think you're right, very good catch, we can go from `WAIT_FOR_FUNDING_CONFIRMED` or `WAIT_FOR_CHANNEL_READY` to `CLOSING` by receiving an error, and then go to `CLOSED` if we realize that the funding transaction actually cannot be published. That transition from `CLOSING` to `CLOSED` doesn't generate any of the two events.

I think that a transition from `WAIT_FOR_FUNDING_CONFIRMED` or `WAIT_FOR_CHANNEL_READY` to `CLOSING` should trigger a `ChannelAborted`, what do you think?

**Review by remyers — COMMENTED** [review]
Looks good! I rifted on your tests for the ready and transient states in [5713779](https://github.com/ACINQ/eclair/pull/2593/commits/5713779374d12769ed6aad6df69e5d04470a4d75)

(I meant to push them to my remote, but I guess it ended up in your branch)

**Comment by t-bast** [comment]
> Looks good! I rifted on your tests for the ready and transient states in [5713779](https://github.com/ACINQ/eclair/pull/2593/commits/5713779374d12769ed6aad6df69e5d04470a4d75)
> (I meant to push them to my remote, but I guess it ended up in your branch)

I reviewed your commit, and it only adds tests which looks good, so I'm keeping it, thanks!
I fixed the failing tests in https://github.com/ACINQ/eclair/pull/2593/commits/3f295c8e1698f18e31ea6e93a221ca3928256499, should be ready to review now.

**Comment by remyers** [comment]
> I reviewed your commit, and it only adds tests which looks good, so I'm keeping it, thanks!
> I fixed the failing tests in [3f295c8](https://github.com/ACINQ/eclair/commit/3f295c8e1698f18e31ea6e93a221ca3928256499), should be ready to review now.

Looks good; I was also looking at those failures and noticed a few more places we could check for `ChannelAborted` in those files. If you think the changes in [be6ab3c](https://github.com/remyers/eclair/commit/be6ab3c3ca53bc58c43de16c69e5a55c2948bb9d) are not too pendantic, then they might be worth adding. At some point when the `Channel` FSM is refactored they could be useful to have.

**Review by remyers — APPROVED** [review]
Looks good! 

Although the changes were simple enough, it was hard to figure out the best way to confirm `ChannelAborted` was emitted when expected. Looking at the FSM was difficult (though educational). Looking at and instrumenting the tests gave me more confidence that the state machine was emitting them when expected.

**Comment by t-bast** [comment]
I added more tests based on your commit in https://github.com/ACINQ/eclair/pull/2593/commits/82221966933c43d383e8145da6f4e8f2fa879364

**Review by remyers — APPROVED** [review]
Looks good! Nice to have all the tests instrumented for `ChannelAborted` now.

**Pull request merged**
