### PR TITLE
Move reusable API parts to a trait

### PR DESCRIPTION
**Pull request by btcontract**
This takes all reusable parts from `Service` trait and puts them into a more generally applicable `AbstractService` trait. The goal is to provide reusable parts for plugins which would establish API of their own (HC is such a plugin).

### CODE REVIEW

**Comment by btcontract** [comment]
`Materializer` is not needed as of akka 2.6 (https://stackoverflow.com/questions/58768399/akka-stream-2-6-how-to-create-actormaterializer)

**Comment by btcontract** [comment]
What about this one, especially in light of https://github.com/ACINQ/eclair/issues/1640?

FWIW my opinion is current approach is good for these reasons:
1. API is a basic function which users expect to be packaged, not optional.
2. Once boilerplate code is factored out defining API becomes pretty straightforward both in core and plugins.
3. Having a common base interface feels better than letting each API-enabled plugin to build this completely from scratch.

**Comment by t-bast** [comment]
We have plans to heavily re-work the JSON API in the not-too-distant future, so I don't think we'll take in changes like the ones you propose until we've figured out where we want to go in more details.

Extending the API for custom nodes can very easily be done in a fork for now, it's a part that doesn't move much so it's easy to keep up-to-date with `master`.

**Comment by btcontract** [comment]
This is somewhat unfortunate as I hope to be not the only plugin user. Maybe this can be used as temporary solution for the next release for example, and on next releases with API changes I'll update accordingly. If not I guess I'll just copy-paste current API code into plugin which is a bit ugly but will work.

**Comment by btcontract** [comment]
Will keep it open to give it a chance to be considered still.

**Comment by btcontract** [comment]
Just forgot about this one, not relevant any more indeed.

**Pull request closed without merging**
