### PR TITLE
Entrypoint for dockerfile and documentation to setup the eclair.conf

### PR DESCRIPTION
**Pull request by NicolasDorier**
Add `entrypoint.sh` to eclair with extensibility point to setup the configuration.

### CODE REVIEW

**Comment by NicolasDorier** [comment]
Rebased

**Comment by pm47** [comment]
I'm no docker expert, but is there any way we can do the same without a separate entrypoint script?

**Comment by NicolasDorier** [comment]
why is it a problem? The entrypoint script is a kind of best practice. Most dockerized application use that.

**Comment by NicolasDorier** [comment]
example for postgres https://github.com/docker-library/postgres/blob/1805adb0693d9602bfb19b6bf2583b311c43b749/10/Dockerfile

**Comment by pm47** [comment]
IIUC you are using `ECLAIR_CONFIG` to set values in the configuration file, but it seems a little at odd with how we handle environment variables currently. They are used to override the configuration file but are not persisted, see:
https://github.com/ACINQ/eclair/blob/44f7bd7145951884f39391d6c023dd1c3e3e48b3/eclair-core/src/main/scala/fr/acinq/eclair/NodeParams.scala#L70-L76

Also, using jvm environment variables would be more "java-ish" and allow passing other arguments to the jvm (memory, etc.).

So, how about we use this `entrypoint.sh` instead?
```bash
#!/bin/bash
set -e

if [[ "$1" == "eclair-node" ]]; then
    mkdir -p "$ECLAIR_DATADIR"
    java $JAVA_ARGS -Declair.datadir="$ECLAIR_DATADIR" -jar eclair-node.jar
else
    exec "$@"
fi

```

Which I run like so:
`docker run -p 8080 -e JAVA_ARGS="-Xmx512m -Declair.api.binding-ip=0.0.0.0 -Declair.node-alias=node-pm -Declair.printToConsole" 2ce4ff9e1ced eclair-node`

Also I like a lot the fact that the datadir can be persisted on the host, but is it really necessary to allow overriding its location on the docker image (`ECLAIR_DATADIR`)?

**Comment by NicolasDorier** [comment]
```
Also, using jvm environment variables would be more "java-ish" and allow passing other arguments to the jvm (memory, etc.).
```

ENTRYPOINT is like the default program to run. The default arguments are CMD.
What is very used is to pass additional arguments to the java process via CMD.
This is the best way to do as docker is really runned like a packages application.

Concretely we should be able to do:

`docker run ACINQ/eclair -Xmx512m -Declair.api.binding-ip=0.0.0.0 -Declair.node-alias=node-pm -Declair.printToConsole` This would make it even simpler than what you want.

I will update the entrypoint.

```
 They are used to override the configuration file but are not persisted, see:
```

They are, they are inside the /data volume which, if mapped, is persisted.

Anyway, I missed that it was possible to pass the arguments via command line. I think this is better, will update soon.

**Comment by NicolasDorier** [comment]
Actually turns out I can ditch the entrypoint completely by doing so... trying now.

**Comment by NicolasDorier** [comment]
Ok so I was not able to remove the `entrypoint.sh` because of the mandatory ordering of parameters in for java process.
However:

* I ditched the ECLAIR_CONFIG
* You can pass parameters easily to the image, as if you were dealing directly with the java program.

**Comment by NicolasDorier** [comment]
* Updated the possibility to use `JAVA_ARGS` as suggested @pm47

**Comment by pm47** [comment]
I played with it a little bit today and ended it with this dockerfile and ditching entrypoint.sh:
```
...
ENV ECLAIR_DATADIR=/data
RUN mkdir -p "$ECLAIR_DATADIR"
VOLUME [ "/data" ]

ENTRYPOINT java $JAVA_OPTS -Declair.datadir=$ECLAIR_DATADIR -jar eclair-node.jar
```

Which I think does what we want? (got my inspiration from [here](https://github.com/docker-library/docs/tree/master/jetty) and [there](https://github.com/docker-library/docs/tree/master/jenkins))

Do you really want to be able to pass the args after the command? Tbh, we flip-flopped around doing that at the eclair level and finally removed it...

**Comment by NicolasDorier** [comment]
well, it feel a bit dirty to me, as an image should be seen as a normal program which we pass directly arguments. But well, this is not such a big deal.

**Comment by NicolasDorier** [comment]
will update this PR.

**Comment by NicolasDorier** [comment]
@pm47 updated the README to use `$JAVA_OPTS` and removing the entrypoint.

**Comment by pm47** [comment]
> it feel a bit dirty to me, as an image should be seen as a normal program which we pass directly arguments

I think it's better this way because it preserves the behavior of eclair, which is arguably dirty for the same reasons. When/if we switch from env variables to cmdline arg in eclair we'll update the docker image, sounds good?

**Comment by NicolasDorier** [comment]
yep, good to me!

**Pull request merged**
