### PR TITLE
Add channel fees and capacity to Channel GUI

### PR DESCRIPTION
**Pull request by n1bor**
Fix issues with gui being updated from wrong threads
Add more logging to SimpleSupervisor to ensure any actor crashes
are logged.

### CODE REVIEW

**Comment by n1bor** [comment]
Anyone planning to review? Would rather add any review changes at same time as fixing the merge conflict...

**Comment by dpad85** [comment]
Hi @n1bor, thanks for your PR and your patience, i've pushed on your branch a few changes:

* the amounts were not displayed in the user preferred unit
* fee proportional millionth is displayed as a percentage, otherwise it's a bit obscure
* some indentations issues in the code

The capacity was removed from `ChannelDiscovered` in b75962a57f43b31518c296584dfdae3bead31bce, I solved the conflict for now by removing the capacity column. We have to update the database to solve this, i'll push a commit soon.

**Comment by dpad85** [comment]
The additional log you added to SimpleSupervisor was in fact redundant because logging was already enabled for this strategy.

The channel capacity is now saved in the network DB following its removal in https://github.com/ACINQ/eclair/commit/b75962a57f43b31518c296584dfdae3bead31bce.

Thank again!

**Comment by n1bor** [comment]
@dpad85 on the extra logging in SimpleSupervisor you need to check. Code was throwing "concurrent modification exceptions in GuiUpdater due to reads from maps changeg by gui thread. These restarts of the GuiUpdater thread were logged as one line entries ( I think:

akkor.x.y.z WARN GuiUpdater : null

was really not obvious that this was an actor restart nor that we were losing a message. There was no logging of what the exception was nor line number etc... Until I changed the logging in SimpleSupervisor was impossible to know cause/issue.

I know here this is a trival gui update we miss. But elsewhere in the code could easily be a money losing bug and would expect the exception that causes a message to be dropped and actor to restart/resume to always be logged. This is not the case at the moment despite the logging being enabled. I checked the akka source code and it just logs a WARN with no info on what exception caused the restart.

**Comment by dpad85** [comment]
That's a good point, the default logger does not bring enough information. I'll make a PR to put this additional logging back into the supervisor.

**Pull request merged**
