### PR TITLE
Make Integration tests work in macos

### PR DESCRIPTION
**Pull request by joemphilips**
#156

### CODE REVIEW

**Comment by pm47** [comment]
Thanks @joemphilips! Having those tests run on macos is nice

@sstone can you please d/l the binary, verify the sigs and double check the hashes?

**Comment by pm47** [comment]
@joemphilips I am assuming the tests pass? 😄

**Comment by joemphilips** [comment]
@pm47 `mvn clean test` in `eclair-core` passes. But not in top directory.
I'm thinking to work for it and send another PR. But not sure how long it will take since I'm new to jvm world.

**Comment by joemphilips** [comment]
Oh no wait. Yes It passes even running from root dir.
any way, I think there are no problem for merging. Please tell me if there are something wrong.

**Pull request merged**
