### PR TITLE
Update kamon

### LINKED ISSUE #1410: v0.4 upgrade to Akka 2.6 which I think broke Kamon monitoring
Getting this error:
```
2:20:28.254 [,] ERROR  fr.acinq.eclair.gui.FxPreloader - java.lang.ClassCastException: class akka.dispatch.ForkJoinExecutorConfigurator$ForkJoinExecutorServiceFactory cannot be cast to class kamon.instrumentation.akka.instrumentations.DispatcherInfo$HasDispatcherName (akka.dispatch.ForkJoinExecutorConfigurator$ForkJoinExecutorServiceFactory and kamon.instrumentation.akka.instrumentations.DispatcherInfo$HasDispatcherName are in unnamed module of loader 'app')
	at kamon.instrumentation.akka.instrumentations.CopyDispatcherInfoToExecutorServiceFactory$.exit(DispatcherInstrumentation.scala:126)
	at akka.dispatch.ForkJoinExecutorConfigurator.createExecutorServiceFactory(ForkJoinExecutorConfigurator.scala:108)
	at akka.dispatch.Dispatcher.<init>(Dispatcher.scala:53)
	at akka.dispatch.DispatcherConfigurator.<init>(Dispatchers.scala:278)
	at akka.dispatch.Dispatchers.configuratorFrom(Dispatchers.scala:239)
	at akka.dispatch.Dispatchers.lookupConfigurator(Dispatchers.scala:154)
	at akka.dispatch.Dispatchers.lookup(Dispatchers.scala:120)
	at akka.dispatch.Dispatchers.<init>(Dispatchers.scala:107)
	at akka.actor.ActorSystemImpl.<init>(ActorSystem.scala:964)
	at akka.actor.ActorSystem$.apply(ActorSystem.scala:283)
	at akka.actor.ActorSystem$.apply(ActorSystem.scala:327)
	at akka.actor.ActorSystem$.apply(ActorSystem.scala:271)
```
This is the fix
https://github.com/kamon-io/kamon-akka/commit/073c05cb22c8e6d97255f2ff63005847285c2665
So need version 2.0.1 - we are on 2.0.0

### PR DESCRIPTION
**Pull request by t-bast**
Update Kamon libraries.
Remove log spam in PostRestartHtlcCleaner.

Fixes #1410

### CODE REVIEW

**Comment by pm47** [comment]
How come we didn't stumble into this ourselves?

We probably can get rid of `kamon.version` since each sub module has its own independent version.

**Comment by sstone** [comment]
Latest version for kamon (kamon-akka, kamon-apm-reporter, kamon-jdbc, kamon-system-metrics) is 2.1.0. Here we use 3 different, similar versions (2.0.2, 2.0.3, 2.0.5) which is a bit confusing. Unless there's a good reason for using different versions for the kamon modules, have a proper definition for `kamon.version` is cleaner.

**Comment by t-bast** [comment]
Agreed @sstone, I used the versions we are currently using on our nodes because we know they work. PM is currently testing version 2.1.0, if that works I'll update the PR with that!

**Comment by pm47** [comment]
> Unless there's a good reason for using different versions for the kamon modules

They have the habit of starting from a base version for all modules, then independently update each module. That's why it's a bit difficult to factor.

**Pull request merged**
