### PR TITLE
Fix edges with empty capacity in the routing graph

### PR DESCRIPTION
**Pull request by t-bast**
Light clients don't always validate channels by fetching the blockchain tx.
That means they don't have access to the exact capacity.
When that happens, we should fallback to `htlc_maximum_msat` if available, or to a default capacity (otherwise path-finding will ignore these edges).

### CODE REVIEW

**Comment by sstone** [comment]
LGTM, but it's a bit difficult to test as I don't think it's covered by our unit tests yet (on master capacity is correct as we get it from the blockchain, on android it's not but "A->B->C" type tests are disabled as we don't relay payments which is why this issue was not detected before, and on phoenix it's not relevant).
I'll test on android and add a comment.

**Comment by t-bast** [comment]
Actually this doesn't cover all the way we can create the graph. Wait before testing on android, I need to add another commit to cover everything.

**Comment by t-bast** [comment]
You should be good now, I was missing the helper method we use to create the graph initially from the DB.

**Comment by sstone** [comment]
I checked that it does fix route computation on Android.

**Pull request merged**
