### PR TITLE
Relay HTLC failure when inactive revoked commit confirms

### PR DESCRIPTION
**Pull request by t-bast**
When an inactive revoked commitment containing outgoing HTLCs is confirmed, we must consider the outgoing HTLC failed and relay that failure upstream. Because of the alternative commit tx mechanism, those inactive revoked commitments match the remote commit, so we were waiting for tx confirmation before failing back upstream.

This bug was found when testing splicing with HTLCs on `lightning-kmp`.

### CODE REVIEW

**Review by remyers — COMMENTED** [review]
I confirmed that running the test `force-close with multiple splices (inactive revoked, quiescence)` without the change to `overriddenOutgoingHtlcs` will now trigger an error. This happens because without this fix the check if `remoteCommit` is in the `d.revokedCommitPublished` set is not performed before the check that `remoteCommit` confirmed.

In this test, the `remoteCommit` for bob is their commit from the confirmed `splice1` funding tx, which is revoked when `splice2` is negotiated. The htlcs from alice to bob should be failed, but without this fix the `remoteCommit` is treated as a valid commit for `splice1` without checking if it was revoked.

Am I understanding things correctly? 

If Alice forwarded, but does not settle, an htlc to Bob after `splice2` is negotiated, that should also be failed, right? I don't see this behavior when I modify the test, am I missing something?

**Comment by remyers** [comment]
> If Alice forwards, but does not settle, an htlc to Bob after `splice2` is negotiated, that htlc should also be failed, right? I don't see this behavior when I modify the test, am I missing something?

I tried to demonstrate the problem and a potential solution in [3c6f58c](https://github.com/remyers/eclair/commit/3c6f58c8ca9f32ac65017efc1f2091c47586c25c).

**Comment by t-bast** [comment]
> Am I understanding things correctly?

Yes, that's exactly it! And the reason that a `remoteCommit` ends up matching a revoked commit is because of the way we handle inactive commitments from previous splices, where we replace our commitments data with the commitment that confirms: https://github.com/ACINQ/eclair/blob/3a49f5dd432aed8fdaba45b1214525d166864d57/eclair-core/src/main/scala/fr/acinq/eclair/channel/fsm/Channel.scala#L1621

> If Alice forwards, but does not settle, an htlc to Bob after splice2 is negotiated, that htlc should also be failed, right? I don't see this behavior when I modify the test, am I missing something?

That's a very good catch, thanks for noticing that! This is another subtlety: because of the way we replace our commitments data, we end up losing information about HTLCs that have been added *after* the revoked one, so we weren't able to automatically notify the upstream channels that those HTLCs are gone downstream. This should be fixed this in https://github.com/ACINQ/eclair/pull/2801/commits/18754cf9aeb3592742825ea5d1883b70b27b5113

**Review by remyers — APPROVED** [review]
Good idea to just immediately fail the htlcs when the revoked commitment confirms and the remote commitment is overridden. Looks good to me!

**Pull request merged**
