### PR TITLE
Kamon-Prometheus Monitoring

### PR DESCRIPTION
**Pull request by GoutamVerma**
- Added dependencies which will start exporting metrics to Prometheus endpoint.

Note : The default configuration is enough to expose metrics to Prometheus endpoint. visit http://localhost:9095/metrics to see exposed metrics.  but we need tweaking the default bucketing configuration for Histogram metrics. You can find more information [here](https://kamon.io/docs/latest/reporters/prometheus/#configuration) and this all things will goes in `eclair.conf` file

### CODE REVIEW

**Comment by t-bast** [comment]
We cannot just merge this PR as-is, this is very incomplete.
Can you add to this PR the following things?

First of all, add a default configuration for the prometheus endpoint in `reference.conf`:

```conf
// See documentation here: https://kamon.io/docs/latest/reporters/prometheus/
kamon.prometheus {
  embedded-server {
    hostname = 0.0.0.0
    port = 9095
  }
}
```

Second, can you find a way of disabling prometheus for users who don't wish to use it? When disabled, we'd like eclair not to waste time creating the `metrics.txt` file nor exposing an http endpoint at `0.0.0.0:9095`.

Once both of these things are complete, we can merge the PR and move to the next step: configuring the buckets based on what data we expect eclair to create and add grafana dashboards.

**Comment by GoutamVerma** [comment]
> First of all, add a default configuration for the prometheus endpoint in `reference.conf`:

Okay, I will add this in `reference.conf` for default configuration.
```
  // See documentation here: https://kamon.io/docs/latest/reporters/prometheus/
  kamon.prometheus {
    include-environment-tags = true
    embedded-server {
      hostname = 0.0.0.0
      port = 9095
    }
  }
```

> Second, can you find a way of disabling prometheus for users who don't wish to use it? When disabled, we'd like eclair not to waste time creating the `metrics.txt` file nor exposing an http endpoint at `0.0.0.0:9095`.

yes In order to disable Prometheus, users needs to add ` start-embedded-http-server = no` in eclair.conf file [see this](https://github.com/kamon-io/kamon-prometheus/blob/master/src/main/resources/reference.conf#:~:text=start%2Dembedded%2Dhttp%2Dserver%20%3D%20yes)

**Comment by GoutamVerma** [comment]
> start-embedded-http-server = no

Mentor, Is it reasonable to add this in `reference.conf `?

**Comment by t-bast** [comment]
Yes, please add them to `reference.conf` ASAP so that we can merge this first PR.
You should make prometheus disabled by default in `reference.conf`, with comments explaining to users how to enable it.

**Comment by GoutamVerma** [comment]
> Yes, please add them to `reference.conf` ASAP so that we can merge this first PR. You should make prometheus disabled by default in `reference.conf`, with comments explaining to users how to enable it.

I have added all the stuff and disabled Prometheus by default in `reference.conf`. I think now our PR is ready to merge

**Comment by GoutamVerma** [comment]
> please cherry-pick that commit and add it to the PR.

Thanks mentor for the commits, I will cherry-pick them.
 
>(there must be some additional Kamon configuration to do to tell it that we're only using Prometheus and not the Kamon APM reporter).

Yes definitely, there is an option for disabling Kamon APM reporter. To disable it we suppose set `enabled=no` in eclair.conf 
```
kamon.modules {
  apm-reporter {
    enabled = no
  }
} 
```
But disabling apm reporter will report another warning 
`2022-06-14 19:31:28,676 WARN  kamon.Init - Failed to attach the instrumentation because the Kamon Bundle is not present on the classpath` (complete [eclair.logs](https://github.com/ACINQ/eclair/files/8900862/eclair.txt) ).

more info [here](https://github.com/kamon-io/kamon-apm-reporter/blob/master/kamon-apm-reporter/src/main/resources/reference.conf#:~:text=%7D-,kamon.modules%20%7B,%7D,-%C2%A9%202022%20GitHub%2C%20Inc). 
 
>Have a look at the extensive github documentation to learn the best practices: https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/proposing-changes-to-your-work-with-pull-requests

Thanks mentor for doc, I will keep tips in my mind and will create branch for upcoming PR and modify this one also!

**Comment by GoutamVerma** [comment]
> ```
> kamon.modules {
>   apm-reporter {
>     enabled = no
>   }
> } 
> ```

Is there need to add "How to disable apm reporter?" in doc

**Comment by t-bast** [comment]
> Is there need to add "How to disable apm reporter?" in monitoring doc

Of course, how will node operators know how to do this if it's not documented?

**Comment by t-bast** [comment]
Please don't ask before adding things, this is a waste of time. Add them, and if more is needed, I will add comments when reviewing the latest state of the PR.

**Comment by GoutamVerma** [comment]
> Please don't ask before adding things, this is a waste of time. Add them, and if more is needed, I will add comments when reviewing the latest state of the PR.

Sorry for inconvenience, I have opened new PR and in that I added commits in `Prometheus' branch.

**Pull request closed without merging**
